spring:
  jackson:
      serialization:
        write-dates-as-timestamps: true
  # 数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/python?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false


#mybats配置
mybatis-plus:
  configuration:
    cache-enabled: false
  mapper-locations: classpath:mapper/*.xml

server:
  max-http-header-size: 8192000
  port: 8080



